apiVersion: v1
kind: Pod
metadata:
  name: see-db-debug
  namespace: default
spec:
  containers:
  - name: see-db
    image: postgres:9.6
    command: ['sleep']
    args: ['100000']
    env:
    - name: PGDATABASE
      value: postgres
    - name: PGHOST
      valueFrom:
        secretKeyRef:
          name: db-conn
          key: endpoint
    - name: PGUSER
      valueFrom:
        secretKeyRef:
          name: db-conn
          key: username
    - name: PGPASSWORD
      valueFrom:
        secretKeyRef:
          name: db-conn
          key: password
    - name: PGPORT
      valueFrom:
        secretKeyRef:
          name: db-conn
          key: port
