apiVersion: gcp.crossplane.io/v1alpha3
kind: Provider
metadata:
  name: gcp-provider
spec:
  projectID: crossplane-playground
  credentialsSecretRef:
    namespace: crossplane-system
    name: gcp-creds
    key: key
